import type { ApiEndpoint } from "./types";

export const API_DOC_ENDPOINTS: ApiEndpoint[] = [
  {
    method: "POST",
    path: "/api/analysis-jobs",
    category: "analysis",
    summary: "Submit a trackable analysis job",
    description: "Queues differential, Spearman, phenotype-association, or cross-study analysis and returns an opaque job ID for polling.",
    defaultBody: {
      kind: "diff-analysis",
      payload: { group_a_filter: { disease: "IBD" }, group_b_filter: { disease: "NC" } },
    },
    responseSchema: [
      "job_id: string",
      "kind: string",
      "status: queued | running | completed | failed",
      "created_at: string",
    ],
    errorCodes: [400, 429, 500],
  },
  {
    method: "GET",
    path: "/api/analysis-jobs/{job_id}",
    category: "analysis",
    summary: "Poll a trackable analysis job",
    description: "Returns the current status and, when complete, the analysis result for a known job ID.",
    params: [
      { name: "job_id", type: "string", required: true, description: "Job ID returned by the submit endpoint." },
    ],
    responseSchema: [
      "job_id: string",
      "status: queued | running | completed | failed",
      "result: object (when completed)",
      "error: string (when failed)",
    ],
    errorCodes: [404, 429, 500],
  },
  {
    method: "GET",
    path: "/api/health",
    category: "overview",
    summary: "Service health check",
    description: "Returns service status and confirms that the active FastAPI process is reachable.",
    responseSchema: [
      "status: string",
      "service: string",
      "timestamp: string",
    ],
    errorCodes: [429, 500],
  },
  {
    method: "GET",
    path: "/api/project-list",
    category: "studies",
    summary: "Project browser payload",
    description: "Returns project summary cards plus per-project metadata for the Studies workspace.",
    responseSchema: [
      "summary.total_projects: number",
      "summary.total_samples: number",
      "projects[].project_id: string",
      "projects[].country_list: string[]",
      "projects[].n_diseases: number",
    ],
    errorCodes: [429, 500],
  },
  {
    method: "GET",
    path: "/api/project-timeline",
    category: "studies",
    summary: "Publication timeline",
    description: "Aggregates projects by publication year for the Studies timeline chart.",
    responseSchema: [
      "timeline[].year: number",
      "timeline[].projects: number",
      "timeline[].samples: number",
    ],
    errorCodes: [429, 500],
  },
  {
    method: "GET",
    path: "/api/disease-studies",
    category: "studies",
    summary: "Disease-linked study list",
    description: "Returns study coverage for one disease, including sample counts and project identifiers.",
    params: [
      { name: "disease", type: "string", required: true, description: "Disease name, e.g. IBD or CRC." },
    ],
    defaultQuery: { disease: "IBD" },
    responseSchema: [
      "disease: string",
      "studies[].project_id: string",
      "studies[].sample_count: number",
      "studies[].country: string",
    ],
    errorCodes: [400, 404, 429, 500],
  },
  {
    method: "GET",
    path: "/api/phenotype-association",
    category: "analysis",
    summary: "Phenotype association scan",
    description: "Compares two phenotype groups with Mann–Whitney U + BH-FDR across genus- or phylum-level taxa.",
    params: [
      { name: "dim_type", type: "string", required: false, description: "sex, age, or disease." },
      { name: "group_a", type: "string", required: false, description: "First phenotype group." },
      { name: "group_b", type: "string", required: false, description: "Second phenotype group." },
      { name: "tax_level", type: "string", required: false, description: "genus or phylum." },
      { name: "min_prevalence", type: "number", required: false, description: "Minimum prevalence in either group." },
      { name: "top_n", type: "integer", required: false, description: "Maximum returned taxa." },
    ],
    defaultQuery: { dim_type: "sex", group_a: "female", group_b: "male", tax_level: "genus", min_prevalence: 0.1, top_n: 100 },
    responseSchema: [
      "group_a: string",
      "group_b: string",
      "results[].taxon: string",
      "results[].effect_size: number",
      "results[].adjusted_p: number",
    ],
    errorCodes: [400, 404, 429, 500],
  },
  {
    method: "GET",
    path: "/api/chord-data",
    category: "analysis",
    summary: "Disease-genus chord payload",
    description: "Builds an aggregated disease-to-genus matrix for the cross-disease chord visualization.",
    params: [
      { name: "top_diseases", type: "integer", required: false, description: "How many diseases to include." },
      { name: "top_genera", type: "integer", required: false, description: "How many genera per disease to include." },
    ],
    defaultQuery: { top_diseases: 8, top_genera: 10 },
    responseSchema: [
      "diseases: string[]",
      "genera: string[]",
      "links[].source: string",
      "links[].value: number",
    ],
    errorCodes: [429, 500],
  },
  {
    method: "GET",
    path: "/api/species-cooccurrence",
    category: "species",
    summary: "Genus partner network",
    description: "Returns top co-occurring genera for one target genus in NC or disease context.",
    params: [
      { name: "genus", type: "string", required: true, description: "Target genus name." },
      { name: "top_k", type: "integer", required: false, description: "Maximum partners to return." },
      { name: "disease", type: "string", required: false, description: "Optional disease context." },
    ],
    defaultQuery: { genus: "Faecalibacterium", top_k: 12 },
    responseSchema: [
      "genus: string",
      "context: string",
      "partners[].genus: string",
      "partners[].r: number",
      "partners[].adjusted_p: number",
    ],
    errorCodes: [400, 404, 429, 500],
  },
  {
    method: "GET",
    path: "/api/cooccurrence",
    category: "network",
    summary: "Co-occurrence network",
    description: "Builds a disease-specific or NC genus network using Spearman or SparCC, with FDR-filtered edges.",
    params: [
      { name: "disease", type: "string", required: false, description: "Optional disease context." },
      { name: "min_r", type: "number", required: false, description: "Minimum absolute correlation threshold." },
      { name: "top_genera", type: "integer", required: false, description: "Top genera used to build the network." },
      { name: "method", type: "string", required: false, description: "Network method: spearman or sparcc." },
    ],
    defaultQuery: { disease: "CRC", min_r: 0.35, top_genera: 30, method: "spearman" },
    responseSchema: [
      "method: string",
      "nodes[].id: string",
      "edges[].source: string",
      "edges[].adjusted_p: number",
      "metrics.density: number",
    ],
    errorCodes: [400, 429, 500],
  },
  {
    method: "POST",
    path: "/api/cross-study",
    category: "studies",
    summary: "Cross-study meta-analysis",
    description: "Runs multi-project meta-analysis and reports random-effects beta, I² heterogeneity, and adjusted meta p-values.",
    defaultBody: {
      project_ids: ["PRJNA389927", "PRJNA763023", "PRJNA396815"],
      disease: "UC",
      taxonomy_level: "genus",
      method: "wilcoxon",
      p_threshold: 0.05,
      min_studies: 2,
    },
    responseSchema: [
      "markers[].taxon: string",
      "markers[].meta_beta: number",
      "markers[].meta_p: number",
      "markers[].adjusted_meta_p: number",
      "markers[].I2: number",
    ],
    errorCodes: [400, 422, 429, 500],
  },
  {
    method: "POST",
    path: "/api/health-index",
    category: "similarity",
    summary: "Weighted GMHI scoring",
    description: "Calculates the Gut Microbiome Health Index using weighted health/disease genera and NC population calibration.",
    defaultBody: {
      abundances: {
        Bacteroides: 18.4,
        Faecalibacterium: 8.2,
        Prevotella: 4.5,
        Roseburia: 3.1,
      },
    },
    responseSchema: [
      "score: number",
      "raw_score_weighted: number",
      "population_percentile: number",
      "health_genera_detail[].contribution: number",
      "per_genus_deviation[].status: string",
    ],
    errorCodes: [400, 422, 429, 500],
  },
  {
    method: "GET",
    path: "/api/health-index/reference",
    category: "similarity",
    summary: "GMHI reference genera",
    description: "Returns full health-associated and disease-associated reference genera used by the GMHI module.",
    responseSchema: [
      "health_genera[].genus: string",
      "health_genera[].adjusted_p: number",
      "disease_genera[].weight: number",
      "nc_stats: object",
    ],
    errorCodes: [429, 500],
  },
  {
    method: "GET",
    path: "/api/download/diff-results",
    category: "download",
    summary: "Download differential results",
    description: "Exports disease-vs-control genus statistics as CSV, TSV, or JSON.",
    params: [
      { name: "disease", type: "string", required: true, description: "Disease name." },
      { name: "top_n", type: "integer", required: false, description: "Maximum result rows." },
      { name: "format", type: "string", required: false, description: "csv, tsv, or json." },
    ],
    defaultQuery: { disease: "IBD", top_n: 50, format: "json" },
    responseSchema: [
      "disease: string",
      "n_disease: number",
      "n_control: number",
      "results[].genus: string",
      "results[].adjusted_p: number",
    ],
    errorCodes: [400, 429, 500],
  },
  {
    method: "GET",
    path: "/api/download/biomarkers",
    category: "download",
    summary: "Download custom-effect-score biomarkers",
    description: "Exports Mann–Whitney U + BH-FDR biomarker results with a custom effect score.",
    params: [
      { name: "disease", type: "string", required: true, description: "Disease name." },
      { name: "lda_threshold", type: "number", required: false, description: "Minimum custom effect score (legacy parameter name retained for compatibility)." },
      { name: "format", type: "string", required: false, description: "csv, tsv, or json." },
    ],
    defaultQuery: { disease: "CRC", lda_threshold: 2, format: "json" },
    responseSchema: [
      "markers[].taxon: string",
      "markers[].effect_score: number",
      "markers[].adjusted_p: number",
      "markers[].disease_mean: number",
      "markers[].control_mean: number",
      "markers[].disease_prevalence: number",
      "markers[].control_prevalence: number",
      "markers[].log2fc: number",
    ],
    errorCodes: [400, 429, 500],
  },
  {
    method: "GET",
    path: "/api/download/cooccurrence",
    category: "download",
    summary: "Download network edge table",
    description: "Exports co-occurrence edges after correlation and FDR filtering.",
    params: [
      { name: "disease", type: "string", required: false, description: "Optional disease context." },
      { name: "min_r", type: "number", required: false, description: "Minimum absolute correlation." },
      { name: "format", type: "string", required: false, description: "csv, tsv, or json." },
    ],
    defaultQuery: { disease: "CRC", min_r: 0.35, format: "json" },
    responseSchema: [
      "edges[].source: string",
      "edges[].target: string",
      "edges[].r: number",
      "edges[].adjusted_p: number",
      "method: string",
    ],
    errorCodes: [400, 429, 500],
  },
  {
    method: "GET",
    path: "/api/download/lifecycle",
    category: "download",
    summary: "Download lifecycle matrix",
    description: "Exports lifecycle stage abundance and alpha-diversity summaries for NC or disease-filtered cohorts.",
    params: [
      { name: "disease", type: "string", required: false, description: "Optional disease filter." },
      { name: "country", type: "string", required: false, description: "Optional country filter." },
      { name: "top_genera", type: "integer", required: false, description: "Top genera included in each row." },
      { name: "format", type: "string", required: false, description: "csv, tsv, or json." },
    ],
    defaultQuery: { top_genera: 10, format: "json" },
    responseSchema: [
      "genera: string[]",
      "data[].age_group: string",
      "data[].sample_count: number",
      "data[].shannon_mean: number",
    ],
    errorCodes: [400, 429, 500],
  },
];

export const API_DOC_CATEGORIES = [
  "all",
  "overview",
  "species",
  "disease",
  "network",
  "analysis",
  "similarity",
  "studies",
  "download",
] as const;
